#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf processor* 0
rm -f constant/polyMesh/boundary


# ----------------------------------------------------------------- end-of-file
